name: Deploy

on:
  push:
    branches: [master]
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Build and deploy website"
        if: github.repository_owner == 'casey-SK'
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          TOKEN: ${{ secrets.PAT }}
